workflows:
  ios:
    name: iOS Workflow
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release archive -archivePath $HOME/Library/Developer/Xcode/Archives/$(date +'%Y-%m-%d')/YourApp.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/Library/Developer/Xcode/Archives/$(date +'%Y-%m-%d')/YourApp.xcarchive -exportPath $HOME/Library/Developer/Xcode/Archives/$(date +'%Y-%m-%d')/YourApp.ipa -exportOptionsPlist ios/exportOptions.plist
    artifacts:
      - $HOME/Library/Developer/Xcode/Archives/$(date +'%Y-%m-%d')/YourApp.ipa/*.ipa
    publishing:
      email:
        recipients:
          - kchafekanade@gmail.com
